import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]

src     = Split("""
main.c
mpu_port.c
""")

path = [cwd]
CPPPATH = path
group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
